[고유값 고유벡터](https://www.mathsisfun.com/algebra/eigenvalue.html)

$$ Ax = \lambda x \rightarrow A = 정방행렬, \lambda 고유값, x = 고유벡터 $$
$$ Ax - \lambda x = Ax - \lambda I x = 0 $$
$$ | Ax - \lambda I | = 행렬식 $$

$$ 5 \times 1 = 5 $$
$$ A \times I = A $$

$$
    A = \begin{bmatrix}
        -6 & 3 \\
        4 & 5
    \end{bmatrix}
$$

$$
    I(단위행렬) = \begin{bmatrix}
        1 & 0 \\
        0 & 1
    \end{bmatrix}
$$

$$ 단위행렬은 어떤것을 곱하였을때 자기 자신이 나오게 하는것 $$

$$
    \lambda\times I = \begin{bmatrix}
        \lambda & 0 \\
        0 & \lambda
    \end{bmatrix}
$$

$$ | A - \lambda I | = 0 $$
$$ 
    \begin{vmatrix}
        -6 -\lambda & 3 \\
        4 & 5 -\lambda
    \end{vmatrix} = 0
$$
$$ (-6-\lambda) (5-\lambda) -3\times 4 = 0 $$

$$ -(6+\lambda) (5-\lambda) -3\times 4 = 0 $$

$$ (6+\lambda) (\lambda-5) -3\times 4 = 0 $$

$$ (6\lambda-30 + \lambda^2 - 5\lambda) -3\times 4 = 0 $$
$$ (\lambda+ -30 + \lambda^2) -3\times 4 = 0 $$

$$ \lambda^2 + \lambda - 42 = 0  \rightarrow \lambda = -6 또는 7 이므로 \lambda는 반대값인 $$ 
$$ \lambda = -7 또는 6 $$

$$ 고유값 6에 대응하는 고유 벡터를 찾자 $$

$$  
    Ax= \begin{bmatrix}
        -6 &3 \\
        4 & 5
    \end{bmatrix} \begin{bmatrix}
    x \\
    y
    \end{bmatrix} = 6 \begin{bmatrix}
    x \\
    y
    \end{bmatrix}
$$

$$ 
    -6x + 3y = 6x \rightarrow -12x +3y =0 \rightarrow 1)
    4x + 5y = 6y \rightarrow 4x -y =0 \rightarrow 2)
$$

$$ y= 4x, x를 1로 하면 y= 4가 됨 $$ 
    
$$
    고유값 6에 해당하는 고유벡터는 \begin{bmatrix}
        1 \\
        4
    \end{bmatrix} 
$$

$$ 벡터의 크기로 나누어주면 고유벡터의 방향이고 크기가 1인 단위 벡터 $$

$$ \begin{bmatrix}
        6 \\
        24
    \end{bmatrix}
    \begin{bmatrix}
        1 \\
        4
    \end{bmatrix} 벡터나 \begin{bmatrix}
        6 \\
        24
    \end{bmatrix}
$$

$$ 벡터는 크기로 나누어주면 결국 크기가 1인 단위벡터가 되고 $$

$$ 고유값은 6인 쌍으로 그 방향으로 6배 늘린 결과가 됩니다$$

$$
    \begin{bmatrix}
        1 \\
        4
    \end{bmatrix},\begin{bmatrix}
        6 \\
        24
    \end{bmatrix} 에서 \begin{bmatrix}
        1 \\
        4
    \end{bmatrix} 는 \sqrt {1\times1+4\times4}로 나누어 준 값이
$$

$$ 크기가 1인 고유값이 6인 단위벡터임 $$

$$  고유값 -7에 대응하는 고유 벡터를 찾자  $$
$$
   Ax =  \begin{bmatrix}
       -6 & 3 \\
       4 & 5
    \end{bmatrix}   \begin{bmatrix}
       x \\
       y
    \end{bmatrix}   =   -7 \begin{bmatrix}
       x \\
       y
    \end{bmatrix}  
$$
$$
    -6x + 3y  = -7x   \rightarrow  x +3y =0 \rightarrow  1) 
    4x + 5y = -7y  \rightarrow 4x +12y =0   \rightarrow  2)  
$$
$$
   y= -\frac{1}{3}x  , x를 1로 하면 y= -\frac{1}{3} 가 됨 
   고유값 6에 해당하는 고유벡터는  \begin{bmatrix}
       1 \\
        -\frac{1}{3} 
    \end{bmatrix} $$
    
$$ 벡터는 크기로 나누어주면 결국 크기가 1인 단위벡터가 되고 고유값은 $$

$$ -7인 쌍으로 그 방향으로 -7배 늘린결과가 됩니다 $$

$$
\begin{bmatrix}
 1 \\
        -\frac{1}{3} 
    \end{bmatrix}  를  \sqrt{1\times1+ (-\frac{1}{3})\times (-\frac{1}{3})} 로 나누어준 값이 $$
$$크기가 1인 고유값이 -7인 단위 벡터임$$

In [1]:
# -7(고유값에 대한 고유벡터를 위의 방식과 동일하게 하세요)

In [2]:
import numpy as np
import cv2

In [3]:
A = np.array([[-6,3],[4,5]])
value, vector = np.linalg.eig(A)
# -7에 대한 고유벡터는 [-9,486833 , -0.24253563] 이고
# 6에 대한 고유벡터는 [ 0.31622777, -0.9701425 ] 이다
for i,j in vector:
    print(np.sqrt(i*i+j*j)) #벡터의 크기가 1

0.9791953479320481
1.020380551847317


In [4]:
def brightness4():
    src = cv2.imread('images/lenna.bmp', cv2.IMREAD_GRAYSCALE)
    if src is None:
        pirnt("이미지 로딩 실패")
        return
    def update(pos):
        dst = src[:] + pos
        for i in dst:
            for j in i:
                if j>250:
                    print(j)
                    
        cv2.imshow('dst',dst)
    cv2.namedWindow('dst')
    cv2.createTrackbar('Brightness','dst',0,50,update)
    update(0)
    cv2.waitKey()
    cv2.destroyAllWindows()

In [5]:
brightness4()

In [6]:
def brightness5():
    src = cv2.imread('images/lenna.bmp', cv2.IMREAD_GRAYSCALE)
    if src is None:
        pirnt("이미지 로딩 실패")
        return
    def update(pos):
        dst = src[:] + int(pos*1/3)
                    
        cv2.imshow('dst',dst)
    cv2.namedWindow('dst')
    cv2.createTrackbar('Brightness','dst',0,100,update)
    update(0)
    cv2.waitKey()
    cv2.destroyAllWindows()

In [7]:
brightness5()

In [8]:
def brightness6():
    src = cv2.imread('images/lenna.bmp', cv2.IMREAD_GRAYSCALE)
    if src is None:
        pirnt("이미지 로딩 실패")
        return
    def update(pos):
        dst = src[:] - int(pos*1/3)
        for i in dst:
            for j in i:
                if j<0 : return
        cv2.imshow('dst',dst)
    cv2.namedWindow('dst')
    cv2.createTrackbar('Brightness','dst',0,100,update)
    update(0)
    cv2.waitKey()
    cv2.destroyAllWindows()

In [9]:
brightness6()

In [10]:
X = np.array([[10,20,30],[40,50,60]])
X+20

array([[30, 40, 50],
       [60, 70, 80]])

In [11]:
import numpy as np
import cv2

def f1():
    src = np.zeros((400,400),np.uint8)
    def v(pos): 
        ad = pos*3
        dst = src[:]+ad
        cv2.imshow('dst',dst)
    cv2.namedWindow('dst')
    cv2.createTrackbar('Brightness','dst',0,100,v)
    v(0)
    cv2.waitKey()
    cv2.destroyAllWindows()

In [12]:
f1()

In [13]:
import numpy as np
import cv2
# 1씩증가할때 10씩 밝아지게, 225가되면 다시 0
def f2():
    src = np.zeros((400,400),np.uint8)
    def v(pos): 
        ad = pos*10
        dst = src[:]+ad
        print(dst)
        if pos == 255:
            dst = src[:]
        cv2.imshow('dst',dst)
    cv2.namedWindow('dst')
    cv2.createTrackbar('Brightness','dst',0,255,v)
    v(0)
    cv2.waitKey()
    cv2.destroyAllWindows()

In [14]:
f2()

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [15]:
import numpy as np
import cv2

# 4구역으로나눠서 각각의 밝기값을 다르게하기
def f3():
    src = np.zeros((400,400),np.uint8)
    h = src.shape[0]//2
    w = src.shape[1]//2
    
    def v(pos): 
        src[:w,:h]+= (pos*1)
        src[:w,h:]+= (pos*5)
        src[w:,:h]+= (pos*7)
        src[w:,h:]+= (pos*3)
#         ad = pos*3
        #dst = src[:]
        cv2.imshow('dst',src)
        
    cv2.namedWindow('dst')
    cv2.createTrackbar('Brightness','dst',0,100,v)
    v(0)
    cv2.waitKey()
    cv2.destroyAllWindows()

In [16]:
f3()

In [17]:
X=np.array([[1,2,3,4],[5,6,7,8]])

In [18]:
X[:1] +=3
X

array([[4, 5, 6, 7],
       [5, 6, 7, 8]])

In [19]:
import numpy as np
import cv2

# f4 함수에 받은 인자수 만큼 분할....
def f4(num):
    src = np.zeros((800,800),np.uint8)
    h = src.shape[0]//2
    w = src.shape[1]//2
    h_2=src.shape[0]//4
    w_2 = src.shape[1]//4
    def v(pos): 

        if num == 2 :
            src[:,:h] += pos*10
            src[:w,:] += pos*5
        elif num == 4 :
            src[:w,:h]+= (pos*1)
            src[:w,h:]+= (pos*5)
            src[w:,:h]+= (pos*7)
            src[w:,h:]+= (pos*3)
        elif num == 8 :
            src[:w,:h]+= (pos*1)
            src[:w,h:]+= (pos*5)
            src[w:,:h]+= (pos*7)
            src[w:,h:]+= (pos*3)
            src[:w_2,:h]+= (pos*10)
            src[:w_2,h:]+= (pos*2)
            src[w:,:h_2]+= (pos*5)
            src[w:,h_2:]+= (pos*15)
        else:
            print("다시입력하세요")
        cv2.imshow('dst',src)
        
    cv2.namedWindow('dst')
    cv2.createTrackbar('Brightness','dst',0,100,v)
    v(0)
    cv2.waitKey()
    cv2.destroyAllWindows()

In [20]:
f4(4)

In [21]:
def cyclic_iter(l, spec_index): #순환(cyclic) 반복(iteraion)
    result =[]
    length = len(l)
    for i in range(length):
        e_index = spec_index%length
        result.append(l[e_index])
        spec_index+=1
    return result

In [22]:
chars = ['a','b','c','d','e','f','g','h','11','13']
print('original list')
print(chars)
spec_index=3
print("\n 특정 인덱스",spec_index)
print(cyclic_iter(chars,spec_index))

spec_index=5
print("\n 특정 인덱스",spec_index)
print(cyclic_iter(chars,spec_index))

original list
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', '11', '13']

 특정 인덱스 3
['d', 'e', 'f', 'g', 'h', '11', '13', 'a', 'b', 'c']

 특정 인덱스 5
['f', 'g', 'h', '11', '13', 'a', 'b', 'c', 'd', 'e']


## 이동 평균(moving averate) 구하기

In [23]:
arr = [1,2,3,7,9,11,23,34,100]
window_size=3

In [24]:
i=0
moving_average=[] #이동 평균을 저장할 빈 list
while i<len(arr) - window_size+1: # 매 윈도우 크기 3마다 반복함
    window = arr[i:i+window_size]# 현재 window를 얻기위해 list에서 i부터 i+window_size를 저장함
    window_average = round(sum(window)/window_size, 2) # 현재 window의 평균계산
    
    moving_average.append(window_average) # 이동 평균 list에 현재 window를 평균저장
    i += 1 # window를 한칸 이동함
moving_average

[2.0, 4.0, 6.33, 9.0, 14.33, 22.67, 52.33]

![moving aerate](./images/moving.jpg)

In [25]:
x_list = [60,120,180,240,480]
y=[]

In [26]:
for i in range(len(x_list)-1): # x_list의 개수-1만큼 반복, x_list가 5이므로 0~3까지
    y.append(int((x_list[i]+x_list[i+1])/2)) 
    # i가 0일경우 x_list의 [0]번째+ x_list[0+1]번째를 더하여 2로나눈값을 추가 
y

[90, 150, 210, 360]

In [27]:
z=[[x_list[0],y[0]]] # z는 [[x_list[0]번째 60, y[0]번째 90 ]] 추가
for i in range(0,len(y)-1): # 0부터 y의개수 -1 만큼 이므로 0~2까지
    z.append([y[i],y[i+1]]) # i가 0일경우 y[0]번째 90, y[0+1]번째 150 추가
z

[[60, 90], [90, 150], [150, 210], [210, 360]]

In [28]:
z.append([y[-1],x_list[-1]]) # y리스트와 x_list의 뒤에서 -1번째 추가
z

[[60, 90], [90, 150], [150, 210], [210, 360], [360, 480]]

In [73]:
def contrast1():
    src= cv2.imread('./images/m.png', cv2.IMREAD_GRAYSCALE)
    if src is None:
        print("파일 로딩 실패")
        return
    s = 2.0
    dst = cv2.multiply(src, s)
    cv2.imshow('src',src)
    cv2.imshow('dst',dst)
    cv2.waitKey()
    cv2.destroyAllWindows()

In [72]:
contrast1()

(427, 432)


In [118]:
import numpy as np
import cv2

def contrast2(s_value):
    src= cv2.imread('./images/m.png', cv2.IMREAD_GRAYSCALE)
    if src is None:
        print("파일 로딩 실패")
        return
    s = np.array([s_value])
    dst = src * s
    dst = np.clip(dst, 0, 255).astype(np.uint8) # np.clip은 자른다는의미 (0에서 255까지), astype은 형변환
    cv2.imshow('src',src)
    cv2.imshow('dst',dst)
    cv2.waitKey()
    cv2.destroyAllWindows()

In [130]:
[contrast2(i) for i in np.arange(1.0,5.0,1.0)]

[None, None, None, None]

np.clip(dst, 0, 255): 이 부분은 NumPy의 clip 함수를 사용하여 dst 배열의 각 요소를 0과 255 사이의 값으로 제한(클리핑)합니다. 이렇게 하면 픽셀 값이 0 미만이거나 255를 초과하는 경우 해당 값을 0 또는 255로 변경합니다. 이 과정은 이미지 데이터를 정규화하여 픽셀 값이 올바른 범위 내에 있도록 보장합니다.

In [104]:
def contrast3(ratio):
    src= cv2.imread('./images/m.png', cv2.IMREAD_GRAYSCALE)
    if src is None:
        print("파일 로딩 실패")
        return
    dst = np.asarray(src * ratio, dtype="uint8")
    cv2.imshow('src',src)
    cv2.imshow('dst',dst)
    cv2.waitKey()
    cv2.destroyAllWindows()

In [105]:
contrast3(1.1)

In [125]:
[contrast3(i) for i in [0,3,0,7,1,5,1,8]]

[None, None, None, None, None, None, None, None]