## Softmax

$$  \begin{eqnarray}
\sigma(y_{i}) = \left(\frac{e^{y_{i}}}{ \sum\limits_{j} e^{y_{j}}}\right)
j = 1,...,n
\end{eqnarray} $$


Normalization and Probabilities with $\sigma(y_{i})$

$$ \begin{eqnarray}
y \rightarrow 
\begin{bmatrix}{2.}\\{1.}\\{0.1}\end{bmatrix} 
\longrightarrow
\left[\frac{e^{y_{i}}}{ \sum\limits_{j} e^{y_{j}}}\right]
\longrightarrow
\begin{bmatrix}{0.7}\\{0.2}\\{0.1}\end{bmatrix} 
= 1
\end{eqnarray}
 $$

<a href="https://syj9700.tistory.com/38"/>Softmax</a>

In [4]:
import numpy as np

In [40]:
data = np.array([2.0,1.0,0.1])
denominator = sum(np.exp(data))
[np.exp(i)/denominator for i in data]

[0.6590011388859679, 0.2424329707047139, 0.09856589040931818]

In [13]:
sum([np.exp(i)/denominator for i in data])

1.0

In [42]:

exp_data1 = []
data1=0
denominator2 =0
for i in data:
    data1 = np.exp(i)
    denominator2 = data1/denominator
    exp_data1.append(denominator2)

sum_ =0
for i in exp_data1:
    sum_ += i
    
exp_data1,sum_

([0.6590011388859679, 0.2424329707047139, 0.09856589040931818], 1.0)

In [18]:
a = [1,2,3]
[np.log(i) for i in a]

[0.0, 0.6931471805599453, 1.0986122886681098]

In [25]:
e = [np.exp(i) for i in a]
e

[2.718281828459045, 7.38905609893065, 20.085536923187668]

In [31]:
a=np.array([1,2,3])
d=sum(np.exp(a))
[np.exp(i)/d for i in a]

[0.09003057317038046, 0.24472847105479767, 0.6652409557748219]

In [32]:
sum([np.exp(i)/d for i in a])

1.0

In [53]:
a1 = [2,3,4,5,8]
a2 = sum([i*3 for i in a1])
a2

66

In [54]:
a=[1,2,3,4,5,6,7]
a_t = sum([np.log(i)*2 for i in a])
a_t

17.05032272213083

In [65]:
a=[1,2,3,4,5,6,7]
a_t = (sum([np.exp(i) for i in a]))+5
a_t

1738.2661359074918

In [87]:
a=[3,4,5]
a1= [np.exp(i) for i in a] #분자
a2= sum([i for i in a1]) #분모
a3 = a1/a2 #분수

In [88]:
a3[:2]

array([0.09003057, 0.24472847])

$$ \sum_{j=0}^{k}cos(\theta_{j}) $$

$$ 360: \theta = 2\pi : x \rightarrow x = \frac{2\pi \theta}{360} $$

In [89]:
# 각도를 radian으로 변환

In [29]:
def deg_to_radian(x):
    return np.pi*x/180

In [163]:
deg_to_radian(180)

3.141592653589793

In [124]:
radian=[deg_to_radian(i) for i in np.arange(-180,180,10)]
radian

[-3.141592653589793,
 -2.9670597283903604,
 -2.792526803190927,
 -2.6179938779914944,
 -2.443460952792061,
 -2.2689280275926285,
 -2.0943951023931953,
 -1.9198621771937625,
 -1.7453292519943295,
 -1.5707963267948966,
 -1.3962634015954636,
 -1.2217304763960306,
 -1.0471975511965976,
 -0.8726646259971648,
 -0.6981317007977318,
 -0.5235987755982988,
 -0.3490658503988659,
 -0.17453292519943295,
 0.0,
 0.17453292519943295,
 0.3490658503988659,
 0.5235987755982988,
 0.6981317007977318,
 0.8726646259971648,
 1.0471975511965976,
 1.2217304763960306,
 1.3962634015954636,
 1.5707963267948966,
 1.7453292519943295,
 1.9198621771937625,
 2.0943951023931953,
 2.2689280275926285,
 2.443460952792061,
 2.6179938779914944,
 2.792526803190927,
 2.9670597283903604]

In [122]:
sum([np.cos(i) for i in radian])

6.661338147750939e-16

In [120]:
sum(np.cos(radian))

6.661338147750939e-16

In [141]:
x = np.arange(-180,180,10)
y = np.array(np.cos([deg_to_radian(i) for i in x]))
for deg,cos_value in zip(x,y):
    if deg == 60 :
        print(cos_value)
    elif deg == 30:
        print(cos_value, np.sqrt(3)/2)

0.8660254037844387 0.8660254037844386
0.5000000000000001


In [143]:
x = np.arange(-180,180,10)
y_cos = np.array(np.cos([deg_to_radian(i) for i in x]))
y_sin = np.array(np.sin([deg_to_radian(i) for i in x]))
sum_ =0
for deg,cos_value, sin_value in zip(x, y_cos,y_sin):
    if not abs((cos_value**2+sin_value**2) -1) < 0.0000001:
        sum_ += 1
sum_

0

In [145]:
x1=0.8660254037844387
x2=0.5000000000000001
(x1*x1) + (x2*x2)

1.0000000000000002

In [147]:
theta = np.cos(3/5)
theta

0.8253356149096783

In [8]:
def radian_to_deg(x):
    return (x/np.pi)*180

In [2]:
vec_=[[10,20],[5,4],[2,-1],[5,3],[-1,2],[2,4],[8,8],[-1,5]]

In [225]:
def vec_t(i,j):
    vec_b=0
    vec_b = np.sqrt((i*i)+(j*j))
    return vec_b

In [231]:
for i,j in vec_:
    print(vec_t(i,j))

22.360679774997898
6.4031242374328485
2.23606797749979
5.830951894845301
2.23606797749979
4.47213595499958
11.313708498984761
5.0990195135927845


In [229]:
theta = [np.arccos(i/vec_t(i,j)) for i,j in vec_]
theta

[1.1071487177940904,
 0.6747409422235525,
 0.46364760900080615,
 0.5404195002705844,
 2.0344439357957027,
 1.1071487177940904,
 0.7853981633974484,
 1.7681918866447774]

In [237]:
theta1=[]
for i in theta:
    theta1.append(radian_to_deg(i))
theta1

[63.43494882292201,
 38.65980825409008,
 26.565051177077994,
 30.963756532073536,
 116.56505117707799,
 63.43494882292201,
 45.00000000000001,
 101.30993247402023]

In [240]:
dict1={"x":[],"y":[],"r":[],"theta":[]}
for i,j in vec_:
    dict1["x"].append(i)
    dict1["y"].append(i)
    for k,v in zip(vec_b_list,theta):
        dict1["r"].append(k)
        dict1["theta"].append(v)
dict1

{'x': [10, 5, 2, 5, -1, 2, 8, -1],
 'y': [10, 5, 2, 5, -1, 2, 8, -1],
 'r': [22.360679774997898,
  6.4031242374328485,
  2.23606797749979,
  5.830951894845301,
  2.23606797749979,
  4.47213595499958,
  11.313708498984761,
  5.0990195135927845,
  22.360679774997898,
  6.4031242374328485,
  2.23606797749979,
  5.830951894845301,
  2.23606797749979,
  4.47213595499958,
  11.313708498984761,
  5.0990195135927845,
  22.360679774997898,
  6.4031242374328485,
  2.23606797749979,
  5.830951894845301,
  2.23606797749979,
  4.47213595499958,
  11.313708498984761,
  5.0990195135927845,
  22.360679774997898,
  6.4031242374328485,
  2.23606797749979,
  5.830951894845301,
  2.23606797749979,
  4.47213595499958,
  11.313708498984761,
  5.0990195135927845,
  22.360679774997898,
  6.4031242374328485,
  2.23606797749979,
  5.830951894845301,
  2.23606797749979,
  4.47213595499958,
  11.313708498984761,
  5.0990195135927845,
  22.360679774997898,
  6.4031242374328485,
  2.23606797749979,
  5.830951894845

In [245]:
for i in dict1['theta']:
    print((abs(np.sin(i)**2+np.cos(i)**2)-1)<0.0000001)

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


In [257]:
v= np.array(vec_)[0]
v_list=[]
for i in np.array(vec_)[1:]:
    v_list.append(np.dot(v,i))

In [5]:
v1 = np.array(vec_)[0] #벡터 0번째와 다른 7개의 내적
v_list1=[]
for i,j in vec_[1:]:
#     print("i",i,"j",j)
    v_list1.append(v1[0]*i+v1[1]*j)
v_list1

[130, 0, 110, 30, 100, 240, 90]

In [15]:
v_ =[np.sqrt(i*i+j*j) for i,j in vec_] # 벡터의 크기
cos_theta = v_list1/np.array([v_[0]*i for i in v_[1:]]) 
# 벡터의 크기0번째 * 나머지 6개 벡터를 곱한값 / 벡터의 내적값 = cos_theta
theta = np.arccos(cos_theta) # cos_theta를 arccos하면 theta(각도)인데 radian
radian_to_deg(theta) # radian각도를 radian_to_deg함수에 넣어서 각도를 구함

array([2.47751406e+01, 9.00000000e+01, 3.24711923e+01, 5.31301024e+01,
       8.53773646e-07, 1.84349488e+01, 3.78749837e+01])

In [17]:
cos_theta

array([0.90795938, 0.        , 0.84366149, 0.6       , 1.        ,
       0.9486833 , 0.78935222])

In [13]:
np.dot(vec_[0],vec_[2])

0

In [23]:
x_ = vec_

In [21]:
def magnitude(x):
    return np.sqrt(sum([i*i for i in x]))

In [22]:
def dot(x,y):
    return sum([i*j for i,j in zip(x,y)])

In [24]:
x_0, x_the_other = x_[0], x_[1:]
x_0_mag = magnitude(x_0)
x_other_mag = [magnitude(i) for i in x_the_other]

In [25]:
other_dot = [dot(x_0,i) for i in x_the_other]

In [31]:
the_other_cos = [dot_i/(x_0_mag*x_m) for dot_i , x_m in zip(other_dot,x_other_mag)]
cos_deg = [radian_to_deg(np.arccos(i)) for i in the_other_cos]
# np.cos(deg_to_radian(cos_deg[2])) - dot(x_[0] ,x_[2])
['수직' if dot(x_[0], i)==0 else '수직아님' for i in x_]

['수직아님', '수직아님', '수직', '수직아님', '수직아님', '수직아님', '수직아님', '수직아님']