In [5]:
import numpy as np # numpy는 모듈, numpy를 np로 쓰겠다고 정의

In [ ]:
X = np.array([3,4,2])
X

In [ ]:
np.shape((X*2))

In [ ]:
np.shape((X*2).T)

In [ ]:
X2 = np.array([[1,2,3,4],[4,5,6,7]])
np.shape(X2)

In [ ]:
Y2 = np.array([[1,2,3,4],[4,5,6,7]]).T
np.shape(Y2)

In [ ]:
np.shape(np.dot(X2,Y2))

$$ X_2 = \begin{bmatrix}
1 & 2 & 3 & 4 \\
4 & 5 & 6 & 7
\end{bmatrix} $$

2행 4열 과 2행 4열의 행렬 곱은 불가능 합니다 <br>
(2x 4) 행렬과 (2x4) 행렬의 곱은 불가능하고 <br>
곱하려는 앞의 행렬의 열(4) 과 곱하려는 행렬의 행이 같아야 계산할 수 있다 <br>
만약 (2x4), (4x3)을 곱하면 결과의 형태는 (2, 3) 열의 형태가 된다

In [ ]:
A1=np.array([2,3])
B1=np.array([3,4])

In [ ]:
print(type(A1))

In [ ]:
np.dot(A1,B1)

In [ ]:
A1[0]*B1[0]+A1[1]*B1[1]

## 벡터의 크기
$$ \overrightarrow{a} =(a_1, a_2, a_3,..., a_{n-1}, a_n)$$
$$ \sqrt{a_1^2+a_2^2+\cdot \cdot\cdot\cdot +a_{n-1}^2+a{n}^2} $$
$$ \sqrt{\sum_{i=0}^na_i^2} $$

## 내적의 정의 
$$ \overrightarrow{a}\cdot \overrightarrow{b}  = 
    (a_1\cdot{b_1}+ a_2\cdot{b_2}+ a_3\cdot{b_3} +,...,+a_{n-1}\cdot{b_{n-1}}+ a_n\cdot{b_{n}} ) 
$$
$$ |a|\cdot|b|cos\theta $$ 
$$  cos\theta  = \frac{\overrightarrow{a}\cdot \overrightarrow{b}}{|a|\cdot|b|} $$
$$ x = cos\theta \rightarrow \theta = cos^{-1}{x} $$

In [ ]:
# |A1|
np.sqrt(A1[0]*A1[0]+A1[1]*A1[1])

In [ ]:
np.dot(A1,B1) #라이브러리
result_dot=0 
# 문제2) 반복문으로 내적하는 코드 구현( 각각의 요소의 곱을 다 더한 결과)
for i in zip(A1,B1):
    result_dot += i[0]*i[1] # 노가다 버전
result_dot == np.dot(A1,B1)

In [8]:
def dot(x1,y1): # 사용자가 정의한 내적함수
    result_dot = 0
    for i in zip(x1,y1):
        result_dot += i[0]*i[1]
    return result_dot

In [ ]:
for i in zip([1,2,3],[4,5,6]):
    print (i)

In [2]:
def abs_vector(x):
    a1_abs=0
    for i in x:
        a1_abs += i*i
    return np.sqrt(a1_abs)  #sqrt는 루트

In [ ]:
abs_vector(A1)

In [ ]:
# |B1|
np.sqrt(B1[0]*B1[0]+B1[1]*B1[1])

In [ ]:
abs_vector(B1)

In [ ]:
np.sqrt(16)

In [9]:
A1=np.array([33,22])
B1=np.array([-2, 3])

In [11]:
cos_theta = dot(A1,B1)/ (abs_vector(A1) * abs_vector(B1))
cos_theta

0.0

$$ 3x+ 2y+4z = 11 $$ 
$$ 2x+ 3y-z = 21 $$ 
$$ -x+ 4y+3z = 7 $$ 
$$  A =  \begin{bmatrix}
3 & 2 & 4 \\
 2& 3 &-1  \\
 -1& 4 & 3  
\end{bmatrix}  $$ 
$$   x =  \begin{bmatrix}
 x\\
 y\\
z
\end{bmatrix} $$

$$   b =  \begin{bmatrix}
 11\\
 21\\
7
\end{bmatrix} $$
$$ Ax = b $$

$$ I = \begin{bmatrix} 
1& 0 & 0 \\
 0& 1 &0  \\
 0& 0 & 1
\end{bmatrix} $$
대각 성분이 1이고 나머지는 0인 행렬을 단위행렬(Identity) 이라 함 <br>
어떤 행렬에 I를 곱하면 자기 자신 <br>
곱셈에 대한 항등원은 1이다
그리고 역원은 어떤숫자에 뭐를 곱했더니 곱셈에 대한 항등원 1이 나오는가? <br>
행렬에서 곱셈의 항등원이 I 이고 <br>
그리고 곱셈의 항등원이 되기 위한 행렬에 어떤 행렬을 곱했더니 행렬의 항등원인 단위 행렬이 나오는가? <br>
$$ AB = BA = I $$
결국 $ B = A^{-1} $ 가 된다
$$ 4x = 1 \rightarrow x = \frac{1}{4} = 4^{-1} $$ 
$ A^{-1} $ 를 A의 역행렬이라 한다

- A의 첫번째 열을 i번 곱해서 각 줄대로 더한값 

In [12]:
A = np.array([[3 , 2 , 4],
[2, 3 ,-1 ],
[-1, 4 , 3]])

In [14]:
I = np.array([[1 , 0 , 0],
[0, 1 ,0 ],
[0, 0 , 1]])

In [15]:
np.dot(A,I)

array([[ 3,  2,  4],
       [ 2,  3, -1],
       [-1,  4,  3]])

In [16]:
b = np.array([11,21,7])

In [29]:
c1 = A.T[0] # A 행렬의 0번 column , T 는 transpose 행(가로)과 열(세로)을 바꾼다
c2 = A.T[1] # A 행렬의 1번 column
c3 = A.T[2] # A 행렬의 2번 column


In [26]:
x= np.dot(np.linalg.inv(A),b) # linalg = linaer algebra모듈 ,inv역함수
x

array([ 3.49315068,  4.04109589, -1.89041096])

In [30]:
x= np.dot(np.linalg.inv(A),b) # linalg = linaer algebra모듈 ,inv역함수 / x = A_1 x b
x[0]*c1 + c2*x[1] + c3*x[2] # A 행렬의 column vector 들 과의 선형 결합으로
# b 벡터 만듬, 그 선형결합하기 위한 값(scaling factor)가 우리가 찾고자 하는 해

array([11., 21.,  7.])